import { mockConversations, mockMessages } from '@/data/mockData';
import { mockList, mockCreate, mockDelete, delay, type ApiResponse } from './api';
import type { Conversation, Message } from '@/types/chat';

let conversations = [...mockConversations];
let messages = [...mockMessages];

export const chatService = {
  listConversations: (): Promise<ApiResponse<Conversation[]>> => mockList(conversations),
  getMessages: async (conversationId: string): Promise<ApiResponse<Message[]>> => {
    await delay();
    return { data: messages.filter((m) => m.conversationId === conversationId), success: true };
  },
  createConversation: (conv: Conversation): Promise<ApiResponse<Conversation>> => mockCreate(conversations, conv),
  deleteConversation: (id: string): Promise<ApiResponse<boolean>> => mockDelete(conversations, id),
  /** Simulate AI response */
  async sendMessage(userMsg: Message, modelId: string, lang: string): Promise<ApiResponse<Message>> {
    messages.push(userMsg);
    await delay(1200 + Math.random() * 800);
    const aiMsg: Message = {
      id: (Date.now() + 1).toString(),
      conversationId: userMsg.conversationId,
      role: 'assistant',
      content: lang === 'vi'
        ? 'Đây là câu trả lời mẫu từ AI. Trong phiên bản thực, câu trả lời sẽ được tạo bởi RAG pipeline dựa trên tài liệu môn học đã upload.'
        : 'This is a sample AI response. In the production version, answers will be generated by the RAG pipeline based on uploaded course materials.',
      tokensUsed: 50,
      modelUsed: modelId,
      createdAt: new Date().toISOString(),
    };
    messages.push(aiMsg);
    return { data: aiMsg, success: true };
  },
  _reset: () => { conversations = [...mockConversations]; messages = [...mockMessages]; },
};
