import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

type Language = 'vi' | 'en';

const translations: Record<string, Record<Language, string>> = {
  // Sidebar navigation
  'nav.dashboard': { vi: 'Dashboard', en: 'Dashboard' },
  'nav.courses': { vi: 'Môn học', en: 'Courses' },
  'nav.chat': { vi: 'Chat AI', en: 'AI Chat' },
  'nav.documents': { vi: 'Tài liệu', en: 'Documents' },
  'nav.quizzes': { vi: 'Quiz', en: 'Quizzes' },
  'nav.users': { vi: 'Người dùng', en: 'Users' },
  'nav.settings': { vi: 'Cài đặt', en: 'Settings' },
  'nav.profile': { vi: 'Tài khoản', en: 'Account' },
  'nav.logout': { vi: 'Đăng xuất', en: 'Sign Out' },
  'nav.accountSettings': { vi: 'Cài đặt tài khoản', en: 'Account Settings' },

  // Roles
  'role.admin': { vi: 'Quản trị viên', en: 'Admin' },
  'role.teacher': { vi: 'Giáo viên', en: 'Teacher' },
  'role.student': { vi: 'Sinh viên', en: 'Student' },

  // Common actions
  'action.save': { vi: 'Lưu thay đổi', en: 'Save Changes' },
  'action.cancel': { vi: 'Hủy', en: 'Cancel' },
  'action.delete': { vi: 'Xóa', en: 'Delete' },
  'action.edit': { vi: 'Chỉnh sửa', en: 'Edit' },
  'action.preview': { vi: 'Xem trước', en: 'Preview' },
  'action.download': { vi: 'Tải xuống', en: 'Download' },
  'action.search': { vi: 'Tìm kiếm...', en: 'Search...' },
  'action.create': { vi: 'Tạo mới', en: 'Create' },
  'action.duplicate': { vi: 'Nhân bản', en: 'Duplicate' },
  'action.share': { vi: 'Chia sẻ', en: 'Share' },
  'action.reset': { vi: 'Khôi phục mặc định', en: 'Reset to Default' },
  'action.start': { vi: 'Bắt đầu', en: 'Start' },
  'action.back': { vi: 'Quay lại', en: 'Back' },
  'action.add': { vi: 'Thêm', en: 'Add' },
  'action.viewDetail': { vi: 'Xem chi tiết', en: 'View Details' },
  'action.viewAll': { vi: 'Xem tất cả', en: 'View All' },
  'action.copyCode': { vi: 'Sao chép mã', en: 'Copy Code' },
  'action.copyLink': { vi: 'Chia sẻ liên kết', en: 'Share Link' },
  'action.send': { vi: 'Gửi', en: 'Send' },
  'action.exit': { vi: 'Thoát', en: 'Exit' },
  'action.answer': { vi: 'Trả lời', en: 'Answer' },
  'action.next': { vi: 'Câu tiếp theo', en: 'Next Question' },
  'action.viewResult': { vi: 'Xem kết quả', en: 'View Results' },
  'action.retry': { vi: 'Làm lại', en: 'Retry' },
  'action.sendMessage': { vi: 'Gửi tin nhắn', en: 'Send Message' },
  'action.changeRole': { vi: 'Đổi vai trò', en: 'Change Role' },
  'action.removeFromCourse': { vi: 'Xóa khỏi môn', en: 'Remove from Course' },
  'action.close': { vi: 'Đóng', en: 'Close' },
  'action.backToList': { vi: 'Quay lại danh sách', en: 'Back to List' },
  'action.goHome': { vi: 'Về trang chủ', en: 'Go to Home' },

  // Dashboard
  'dashboard.title': { vi: 'Dashboard', en: 'Dashboard' },
  'dashboard.greeting.morning': { vi: 'Chào buổi sáng', en: 'Good morning' },
  'dashboard.greeting.afternoon': { vi: 'Chào buổi chiều', en: 'Good afternoon' },
  'dashboard.greeting.evening': { vi: 'Chào buổi tối', en: 'Good evening' },
  'dashboard.admin.subtitle': { vi: 'Tổng quan hệ thống EduAssist', en: 'EduAssist system overview' },
  'dashboard.teacher.subtitle': { vi: 'Quản lý môn học và theo dõi sinh viên', en: 'Manage courses and track students' },
  'dashboard.student.subtitle': { vi: 'Tiếp tục hành trình học tập của bạn', en: 'Continue your learning journey' },

  // Admin Dashboard
  'admin.totalUsers': { vi: 'Tổng người dùng', en: 'Total Users' },
  'admin.activeCourses': { vi: 'Môn học hoạt động', en: 'Active Courses' },
  'admin.processedDocs': { vi: 'Tài liệu đã xử lý', en: 'Processed Documents' },
  'admin.conversations': { vi: 'Cuộc hội thoại', en: 'Conversations' },
  'admin.systemHealth': { vi: 'Sức khỏe hệ thống', en: 'System Health' },
  'admin.serviceStatus': { vi: 'Trạng thái các dịch vụ', en: 'Service Status' },
  'admin.recentRegistrations': { vi: 'Đăng ký gần đây', en: 'Recent Registrations' },
  'admin.newUsersJoined': { vi: 'Người dùng mới tham gia hệ thống', en: 'New users joined the system' },
  'admin.usageByDay': { vi: 'Hoạt động theo ngày', en: 'Daily Activity' },
  'admin.usageByDayDesc': { vi: 'Số lượng chat & quiz trong tuần', en: 'Chats & quizzes this week' },
  'admin.userDistribution': { vi: 'Phân bổ người dùng', en: 'User Distribution' },
  'admin.aiUsage': { vi: 'Sử dụng Token AI', en: 'AI Token Usage' },
  'admin.aiUsageDesc': { vi: 'Thống kê token tháng này', en: 'Token stats this month' },
  'admin.online': { vi: 'Online', en: 'Online' },
  'admin.degraded': { vi: 'Chậm', en: 'Degraded' },
  'admin.traffic': { vi: 'Lưu lượng truy cập hôm nay', en: "Today's Traffic" },
  'admin.comparedLastMonth': { vi: 'so với tháng trước', en: 'compared to last month' },
  'admin.estimatedCost': { vi: 'Chi phí ước tính', en: 'Estimated Cost' },

  // Teacher Dashboard
  'teacher.coursesTaught': { vi: 'Môn học đang dạy', en: 'Courses Teaching' },
  'teacher.totalStudents': { vi: 'Tổng sinh viên', en: 'Total Students' },
  'teacher.docsUploaded': { vi: 'Tài liệu đã upload', en: 'Documents Uploaded' },
  'teacher.quizzesCreated': { vi: 'Quiz đã tạo', en: 'Quizzes Created' },
  'teacher.myCourses': { vi: 'Môn học của tôi', en: 'My Courses' },
  'teacher.myCoursesDesc': { vi: 'Tổng quan hoạt động các môn đang dạy', en: "Overview of courses you're teaching" },
  'teacher.pendingDocs': { vi: 'Tài liệu đang xử lý', en: 'Processing Documents' },
  'teacher.lowPerformance': { vi: 'Sinh viên cần hỗ trợ', en: 'Students Needing Support' },
  'teacher.lowPerformanceDesc': { vi: 'Sinh viên có điểm quiz dưới 50%', en: 'Students with quiz scores below 50%' },
  'teacher.pendingQuestions': { vi: 'câu hỏi mới', en: 'new questions' },
  'teacher.uploadNewDoc': { vi: 'Upload tài liệu mới', en: 'Upload New Document' },
  'teacher.waitingProcess': { vi: 'Chờ xử lý', en: 'Waiting' },

  // Student Dashboard
  'student.courses': { vi: 'Môn học', en: 'Courses' },
  'student.questionsAsked': { vi: 'Câu hỏi đã hỏi', en: 'Questions Asked' },
  'student.quizCompleted': { vi: 'Quiz hoàn thành', en: 'Quiz Completed' },
  'student.avgScore': { vi: 'Điểm trung bình', en: 'Average Score' },
  'student.progress': { vi: 'Tiến độ học tập', en: 'Learning Progress' },
  'student.progressDesc': { vi: 'Các môn đang theo học', en: "Courses you're enrolled in" },
  'student.recentResults': { vi: 'Kết quả Quiz gần đây', en: 'Recent Quiz Results' },
  'student.recentResultsDesc': { vi: 'Lịch sử làm bài', en: 'Quiz history' },
  'student.studyStreak': { vi: 'Chuỗi học liên tiếp', en: 'Study Streak' },
  'student.streakRecord': { vi: 'kỷ lục', en: 'record' },
  'student.days': { vi: 'ngày', en: 'days' },
  'student.askAINow': { vi: 'Hỏi AI ngay!', en: 'Ask AI now!' },
  'student.askAIDesc': { vi: 'Đặt câu hỏi về bất kỳ môn học nào', en: 'Ask questions about any course' },
  'student.chatWithAI': { vi: 'Chat với AI', en: 'Chat with AI' },
  'student.upcomingQuizzes': { vi: 'Quiz sắp tới', en: 'Upcoming Quizzes' },
  'student.examSchedule': { vi: 'Lịch thi sắp tới', en: 'Upcoming Exams' },
  'student.daysLeft': { vi: 'Còn', en: '' },
  'student.daysLeftSuffix': { vi: 'ngày', en: 'days left' },
  'student.room': { vi: 'Phòng', en: 'Room' },
  'student.takeQuiz': { vi: 'Làm bài', en: 'Take Quiz' },

  // Courses
  'courses.title': { vi: 'Môn học', en: 'Courses' },
  'courses.create': { vi: 'Thêm môn học', en: 'Add Course' },
  'courses.search': { vi: 'Tìm kiếm môn học...', en: 'Search courses...' },
  'courses.admin.subtitle': { vi: 'Quản lý tất cả môn học trong hệ thống', en: 'Manage all courses in the system' },
  'courses.teacher.subtitle': { vi: 'Môn học bạn đang giảng dạy', en: 'Courses you are teaching' },
  'courses.student.subtitle': { vi: 'Các môn học bạn đang theo học', en: 'Courses you are enrolled in' },
  'courses.all': { vi: 'Tất cả', en: 'All' },
  'courses.active': { vi: 'Đang mở', en: 'Active' },
  'courses.inactive': { vi: 'Đã đóng', en: 'Closed' },
  'courses.notFound': { vi: 'Không tìm thấy môn học', en: 'No courses found' },
  'courses.notFoundDesc': { vi: 'Thử tìm kiếm với từ khóa khác', en: 'Try a different keyword' },
  'courses.chatAbout': { vi: 'Chat về môn này', en: 'Chat about this course' },
  'courses.lecturer': { vi: 'Giảng viên', en: 'Lecturer' },
  'courses.docs': { vi: 'tài liệu', en: 'documents' },
  'courses.createTitle': { vi: 'Tạo môn học mới', en: 'Create New Course' },
  'courses.createDesc': { vi: 'Thêm môn học mới vào hệ thống', en: 'Add a new course to the system' },
  'courses.code': { vi: 'Mã môn học', en: 'Course Code' },
  'courses.name': { vi: 'Tên môn học', en: 'Course Name' },
  'courses.description': { vi: 'Mô tả', en: 'Description' },
  'courses.semester': { vi: 'Học kỳ', en: 'Semester' },
  'courses.status': { vi: 'Trạng thái', en: 'Status' },
  'courses.statusDesc': { vi: 'Mở cho sinh viên đăng ký', en: 'Open for student enrollment' },
  'courses.createButton': { vi: 'Tạo môn học', en: 'Create Course' },

  // Course Detail
  'courseDetail.settings': { vi: 'Cài đặt', en: 'Settings' },
  'courseDetail.editInfo': { vi: 'Chỉnh sửa thông tin', en: 'Edit Information' },
  'courseDetail.copyCode': { vi: 'Sao chép mã môn', en: 'Copy Course Code' },
  'courseDetail.shareLink': { vi: 'Chia sẻ liên kết', en: 'Share Link' },
  'courseDetail.deleteCourse': { vi: 'Xóa môn học', en: 'Delete Course' },
  'courseDetail.operating': { vi: 'Đang hoạt động', en: 'Active' },
  'courseDetail.students': { vi: 'Sinh viên', en: 'Students' },
  'courseDetail.documents': { vi: 'Tài liệu', en: 'Documents' },
  'courseDetail.quiz': { vi: 'Quiz', en: 'Quizzes' },
  'courseDetail.avgScore': { vi: 'Điểm TB', en: 'Avg Score' },
  'courseDetail.overview': { vi: 'Tổng quan', en: 'Overview' },
  'courseDetail.recentActivity': { vi: 'Hoạt động gần đây', en: 'Recent Activity' },
  'courseDetail.examSchedule': { vi: 'Lịch thi', en: 'Exam Schedule' },
  'courseDetail.quickAccess': { vi: 'Truy cập nhanh', en: 'Quick Access' },
  'courseDetail.chatAI': { vi: 'Chat AI', en: 'AI Chat' },
  'courseDetail.chatAIDesc': { vi: 'Hỏi đáp với trợ lý AI', en: 'Q&A with AI assistant' },
  'courseDetail.takeQuiz': { vi: 'Làm Quiz', en: 'Take Quiz' },
  'courseDetail.viewDocs': { vi: 'Xem tài liệu', en: 'View Documents' },
  'courseDetail.uploadDoc': { vi: 'Tải lên tài liệu', en: 'Upload Document' },
  'courseDetail.uploadDocDesc': { vi: 'Kéo thả file hoặc click để chọn', en: 'Drag & drop or click to choose' },
  'courseDetail.chooseFile': { vi: 'Chọn file', en: 'Choose File' },
  'courseDetail.filename': { vi: 'Tên file', en: 'Filename' },
  'courseDetail.size': { vi: 'Kích thước', en: 'Size' },
  'courseDetail.chunks': { vi: 'Chunks', en: 'Chunks' },
  'courseDetail.status': { vi: 'Trạng thái', en: 'Status' },
  'courseDetail.uploadDate': { vi: 'Ngày tải', en: 'Upload Date' },
  'courseDetail.searchQuiz': { vi: 'Tìm kiếm quiz...', en: 'Search quizzes...' },
  'courseDetail.createQuiz': { vi: 'Tạo Quiz mới', en: 'Create New Quiz' },
  'courseDetail.attempts': { vi: 'Lượt làm', en: 'Attempts' },
  'courseDetail.viewResults': { vi: 'Xem kết quả', en: 'View Results' },
  'courseDetail.takeExam': { vi: 'Làm bài', en: 'Take Exam' },
  'courseDetail.searchStudent': { vi: 'Tìm kiếm sinh viên...', en: 'Search students...' },
  'courseDetail.addStudent': { vi: 'Thêm sinh viên', en: 'Add Student' },
  'courseDetail.addStudentTitle': { vi: 'Thêm sinh viên vào môn học', en: 'Add Student to Course' },
  'courseDetail.addStudentDesc': { vi: 'Nhập email sinh viên để thêm vào môn', en: 'Enter student email to add to course' },
  'courseDetail.studentEmail': { vi: 'Email sinh viên', en: 'Student Email' },
  'courseDetail.progress': { vi: 'Tiến độ', en: 'Progress' },
  'courseDetail.quizDone': { vi: 'Quiz đã làm', en: 'Quizzes Done' },
  'courseDetail.lastActive': { vi: 'Hoạt động cuối', en: 'Last Active' },
  'courseDetail.midterm': { vi: 'Giữa kỳ', en: 'Midterm' },
  'courseDetail.final': { vi: 'Cuối kỳ', en: 'Final' },
  'courseDetail.questions': { vi: 'câu hỏi', en: 'questions' },
  'courseDetail.createdOn': { vi: 'Tạo ngày', en: 'Created on' },
  'courseDetail.quizAvailable': { vi: 'quiz có sẵn', en: 'quizzes available' },
  'courseDetail.viewDetails': { vi: 'Xem chi tiết', en: 'View Details' },
  'courseDetail.sendMessage': { vi: 'Gửi tin nhắn', en: 'Send Message' },
  'courseDetail.removeStudent': { vi: 'Xóa khỏi môn học', en: 'Remove from Course' },

  // Documents
  'docs.title': { vi: 'Tài liệu', en: 'Documents' },
  'docs.subtitle': { vi: 'Quản lý tài liệu môn học cho hệ thống RAG', en: 'Manage course documents for RAG system' },
  'docs.upload': { vi: 'Tải lên tài liệu', en: 'Upload Document' },
  'docs.uploadDesc': { vi: 'Kéo thả file hoặc click để chọn • PDF, DOCX, TXT', en: 'Drag & drop or click to select • PDF, DOCX, TXT' },
  'docs.chooseFile': { vi: 'Chọn file', en: 'Choose File' },
  'docs.total': { vi: 'Tổng tài liệu', en: 'Total Documents' },
  'docs.processed': { vi: 'Đã xử lý', en: 'Processed' },
  'docs.processing': { vi: 'Đang xử lý', en: 'Processing' },
  'docs.totalChunks': { vi: 'Tổng chunks', en: 'Total Chunks' },
  'docs.searchDocs': { vi: 'Tìm kiếm tài liệu...', en: 'Search documents...' },
  'docs.allCourses': { vi: 'Tất cả môn học', en: 'All Courses' },
  'docs.filename': { vi: 'Tên file', en: 'Filename' },
  'docs.course': { vi: 'Môn học', en: 'Course' },
  'docs.size': { vi: 'Kích thước', en: 'Size' },
  'docs.chunks': { vi: 'Chunks', en: 'Chunks' },
  'docs.status': { vi: 'Trạng thái', en: 'Status' },
  'docs.date': { vi: 'Ngày tải', en: 'Upload Date' },
  'docs.statusReady': { vi: 'Sẵn sàng', en: 'Ready' },
  'docs.statusProcessing': { vi: 'Đang xử lý', en: 'Processing' },
  'docs.statusPending': { vi: 'Chờ xử lý', en: 'Pending' },
  'docs.statusError': { vi: 'Lỗi', en: 'Error' },
  'docs.notFound': { vi: 'Không tìm thấy tài liệu', en: 'No documents found' },
  'docs.notFoundDesc': { vi: 'Thử tìm kiếm với từ khóa khác hoặc chọn môn học khác', en: 'Try a different keyword or course filter' },
  'docs.unsupportedFormat': { vi: 'Định dạng không hỗ trợ', en: 'Unsupported format' },
  'docs.notSupported': { vi: 'không phải PDF, DOCX hoặc TXT', en: 'is not PDF, DOCX or TXT' },

  // Quizzes
  'quiz.title': { vi: 'Quiz', en: 'Quizzes' },
  'quiz.createNew': { vi: 'Tạo Quiz mới', en: 'Create New Quiz' },
  'quiz.teacherDesc': { vi: 'Tạo và quản lý bài kiểm tra', en: 'Create and manage quizzes' },
  'quiz.studentDesc': { vi: 'Ôn tập và kiểm tra kiến thức', en: 'Review and test your knowledge' },
  'quiz.aiCreate': { vi: 'Tạo Quiz bằng AI', en: 'Create Quiz with AI' },
  'quiz.aiDesc': { vi: 'Yêu cầu AI tạo câu hỏi ôn tập từ tài liệu môn học', en: 'Ask AI to generate review questions from course documents' },
  'quiz.tryNow': { vi: 'Thử ngay', en: 'Try Now' },
  'quiz.list': { vi: 'Danh sách Quiz', en: 'Quiz List' },
  'quiz.history': { vi: 'Lịch sử làm bài', en: 'History' },
  'quiz.stats': { vi: 'Thống kê', en: 'Statistics' },
  'quiz.questions': { vi: 'câu', en: 'questions' },
  'quiz.searchQuiz': { vi: 'Tìm kiếm quiz...', en: 'Search quizzes...' },
  'quiz.score': { vi: 'Điểm', en: 'Score' },
  'quiz.historyTitle': { vi: 'Lịch sử làm bài', en: 'Quiz History' },
  'quiz.allAttempts': { vi: 'Tất cả các lần làm quiz', en: 'All quiz attempts' },
  'quiz.minutes': { vi: 'phút', en: 'min' },
  'quiz.deletedQuiz': { vi: 'Quiz đã xóa', en: 'Deleted Quiz' },
  'quiz.totalQuiz': { vi: 'Tổng Quiz', en: 'Total Quizzes' },
  'quiz.totalAttempts': { vi: 'Tổng lượt làm', en: 'Total Attempts' },
  'quiz.systemAvg': { vi: 'Điểm TB toàn hệ thống', en: 'System Average' },
  'quiz.aiCreated': { vi: 'Quiz AI đã tạo', en: 'AI-Created Quizzes' },
  'quiz.resultByQuiz': { vi: 'Kết quả theo Quiz', en: 'Results by Quiz' },
  'quiz.explanation': { vi: 'Giải thích', en: 'Explanation' },
  'quiz.questionNum': { vi: 'Câu', en: 'Question' },
  'quiz.noQuizzes': { vi: 'Chưa có quiz nào', en: 'No quizzes yet' },
  'quiz.noQuizzesDesc': { vi: 'Tạo quiz mới để bắt đầu', en: 'Create a new quiz to get started' },
  'quiz.noAttempts': { vi: 'Chưa có lượt làm nào', en: 'No attempts yet' },
  'quiz.noAttemptsDesc': { vi: 'Hoàn thành quiz để xem lịch sử', en: 'Complete a quiz to see history' },
  'quiz.questionOf': { vi: 'Câu', en: 'Q' },
  'quiz.correct': { vi: 'đúng', en: 'correct' },
  'quiz.wrong': { vi: 'sai', en: 'wrong' },
  'quiz.copy': { vi: 'bản sao', en: 'copy' },
  'quiz.quizName': { vi: 'Tên quiz', en: 'Quiz Name' },
  'quiz.chapter': { vi: 'Chương', en: 'Chapter' },
  'quiz.attempts': { vi: 'Lượt làm', en: 'Attempts' },
  'quiz.avgScore': { vi: 'Điểm TB', en: 'Avg Score' },

  // Users
  'users.title': { vi: 'Quản lý người dùng', en: 'User Management' },
  'users.subtitle': { vi: 'Quản lý tài khoản và phân quyền người dùng trong hệ thống', en: 'Manage user accounts and permissions' },
  'users.addUser': { vi: 'Thêm người dùng', en: 'Add User' },
  'users.addUserTitle': { vi: 'Thêm người dùng mới', en: 'Add New User' },
  'users.addUserDesc': { vi: 'Tạo tài khoản mới cho người dùng. Họ sẽ nhận được email xác nhận.', en: 'Create a new account. They will receive a confirmation email.' },
  'users.fullName': { vi: 'Họ và tên', en: 'Full Name' },
  'users.email': { vi: 'Email', en: 'Email' },
  'users.role': { vi: 'Vai trò', en: 'Role' },
  'users.statusLabel': { vi: 'Trạng thái', en: 'Status' },
  'users.createdAt': { vi: 'Ngày tạo', en: 'Created' },
  'users.totalUsers': { vi: 'Tổng người dùng', en: 'Total Users' },
  'users.activeUsers': { vi: 'Đang hoạt động', en: 'Active' },
  'users.searchUsers': { vi: 'Tìm kiếm theo tên, email...', en: 'Search by name, email...' },
  'users.allRoles': { vi: 'Tất cả vai trò', en: 'All Roles' },
  'users.allStatus': { vi: 'Tất cả trạng thái', en: 'All Status' },
  'users.active': { vi: 'Hoạt động', en: 'Active' },
  'users.inactive': { vi: 'Ngừng', en: 'Inactive' },
  'users.activeStatus': { vi: 'Đang hoạt động', en: 'Active' },
  'users.inactiveStatus': { vi: 'Ngừng hoạt động', en: 'Inactive' },
  'users.notFound': { vi: 'Không tìm thấy người dùng', en: 'No users found' },
  'users.notFoundDesc': { vi: 'Thử tìm kiếm với từ khóa khác hoặc thay đổi bộ lọc', en: 'Try a different search or filter' },
  'users.changeRoleTitle': { vi: 'Đổi vai trò', en: 'Change Role' },
  'users.changeRoleDesc': { vi: 'Chọn vai trò mới cho', en: 'Select a new role for' },
  'users.missingInfo': { vi: 'Thiếu thông tin', en: 'Missing Information' },
  'users.fillRequired': { vi: 'Vui lòng nhập đầy đủ họ tên và email.', en: 'Please fill in full name and email.' },
  'users.user': { vi: 'Người dùng', en: 'User' },
  'users.selected': { vi: 'Đang chọn', en: 'Selected' },

  // Chat
  'chat.newConversation': { vi: 'Cuộc trò chuyện mới', en: 'New Conversation' },
  'chat.selectCourse': { vi: 'Chọn môn học', en: 'Select Course' },
  'chat.placeholder': { vi: 'Nhập câu hỏi của bạn...', en: 'Type your question...' },
  'chat.welcomeTitle': { vi: 'Xin chào! Tôi là EduAssist AI', en: "Hello! I'm EduAssist AI" },
  'chat.welcomeDesc': { vi: 'Hãy hỏi tôi bất kỳ câu hỏi nào về môn học của bạn. Tôi sẽ trả lời dựa trên tài liệu đã được upload.', en: "Ask me any question about your course. I'll answer based on uploaded documents." },
  'chat.attachFile': { vi: 'Đính kèm file', en: 'Attach file' },
  'chat.attachDesc': { vi: 'Kéo thả file vào ô chat hoặc sử dụng trang Tài liệu để upload.', en: 'Drag & drop files or use the Documents page to upload.' },
  'chat.created': { vi: 'Cuộc trò chuyện mới đã được tạo.', en: 'New conversation created.' },
  'chat.page': { vi: 'tr.', en: 'p.' },

  // Settings
  'settings.title': { vi: 'Cài đặt hệ thống', en: 'System Settings' },
  'settings.subtitle': { vi: 'Cấu hình và tùy chỉnh hệ thống EduAssist', en: 'Configure and customize EduAssist' },
  'settings.general': { vi: 'Chung', en: 'General' },
  'settings.llm': { vi: 'LLM', en: 'LLM' },
  'settings.rag': { vi: 'RAG', en: 'RAG' },
  'settings.notifications': { vi: 'Thông báo', en: 'Notifications' },
  'settings.security': { vi: 'Bảo mật', en: 'Security' },
  'settings.appearance': { vi: 'Giao diện', en: 'Appearance' },
  'settings.language': { vi: 'Ngôn ngữ', en: 'Language' },
  'settings.theme': { vi: 'Giao diện', en: 'Theme' },
  'settings.themeLight': { vi: 'Sáng', en: 'Light' },
  'settings.themeDark': { vi: 'Tối', en: 'Dark' },
  'settings.themeLightDesc': { vi: 'Giao diện sáng, dễ đọc ban ngày', en: 'Bright theme, easy to read in daylight' },
  'settings.themeDarkDesc': { vi: 'Giao diện tối, bảo vệ mắt', en: 'Dark theme, easy on the eyes' },
  'settings.themeChoose': { vi: 'Chọn giao diện sáng hoặc tối', en: 'Choose light or dark theme' },
  'settings.langChoose': { vi: 'Chọn ngôn ngữ hiển thị cho toàn hệ thống', en: 'Choose the display language for the entire system' },
  'settings.langVi': { vi: 'Tiếng Việt', en: 'Vietnamese' },
  'settings.langEn': { vi: 'English', en: 'English' },
  'settings.saved': { vi: 'Đã lưu cài đặt', en: 'Settings Saved' },
  'settings.savedDesc': { vi: 'Các thay đổi đã được áp dụng thành công.', en: 'Changes have been applied successfully.' },
  'settings.resetDone': { vi: 'Đã khôi phục mặc định', en: 'Reset to Default' },
  'settings.resetDoneDesc': { vi: 'Cài đặt đã được đặt lại về giá trị mặc định.', en: 'Settings have been reset to default values.' },
  'settings.systemInfo': { vi: 'Thông tin hệ thống', en: 'System Information' },
  'settings.systemInfoDesc': { vi: 'Cấu hình thông tin cơ bản của hệ thống', en: 'Basic system configuration' },
  'settings.siteName': { vi: 'Tên hệ thống', en: 'System Name' },
  'settings.siteDescription': { vi: 'Mô tả', en: 'Description' },
  'settings.systemStatus': { vi: 'Trạng thái hệ thống', en: 'System Status' },
  'settings.systemStatusDesc': { vi: 'Quản lý trạng thái hoạt động của hệ thống', en: 'Manage system operation status' },
  'settings.maintenanceMode': { vi: 'Chế độ bảo trì', en: 'Maintenance Mode' },
  'settings.maintenanceDesc': { vi: 'Tạm ngưng truy cập hệ thống để bảo trì', en: 'Temporarily suspend system access for maintenance' },
  'settings.running': { vi: 'Hoạt động', en: 'Running' },
  'settings.llmConfig': { vi: 'Cấu hình LLM', en: 'LLM Configuration' },
  'settings.llmConfigDesc': { vi: 'Chọn và cấu hình mô hình ngôn ngữ lớn', en: 'Select and configure large language model' },
  'settings.provider': { vi: 'Nhà cung cấp', en: 'Provider' },
  'settings.model': { vi: 'Model', en: 'Model' },
  'settings.apiKeySecure': { vi: 'API key được mã hóa và lưu trữ an toàn', en: 'API key is encrypted and stored securely' },
  'settings.temperature': { vi: 'Temperature', en: 'Temperature' },
  'settings.temperatureDesc': { vi: 'Độ sáng tạo của câu trả lời (0-2)', en: 'Creativity of responses (0-2)' },
  'settings.maxTokens': { vi: 'Max Tokens', en: 'Max Tokens' },
  'settings.maxTokensDesc': { vi: 'Độ dài tối đa của câu trả lời', en: 'Maximum response length' },
  'settings.systemPrompt': { vi: 'System Prompt', en: 'System Prompt' },
  'settings.systemPromptDesc': { vi: 'Cấu hình prompt hệ thống cho chatbot', en: 'Configure the system prompt for chatbot' },
  'settings.systemPromptPlaceholder': { vi: 'Bạn là trợ giảng AI thông minh...', en: 'You are a smart AI teaching assistant...' },
  'settings.systemPromptDefault': { vi: 'Bạn là trợ giảng AI thông minh của hệ thống EduAssist. Nhiệm vụ của bạn là hỗ trợ sinh viên học tập dựa trên tài liệu môn học đã được cung cấp. Trả lời chính xác, dễ hiểu và luôn trích dẫn nguồn từ tài liệu khi có thể.', en: 'You are a smart AI teaching assistant of EduAssist. Your job is to help students learn based on provided course materials. Answer accurately, clearly, and always cite sources from documents when possible.' },
  'settings.ragConfig': { vi: 'Cấu hình RAG Pipeline', en: 'RAG Pipeline Configuration' },
  'settings.ragConfigDesc': { vi: 'Tùy chỉnh quy trình xử lý tài liệu và tìm kiếm', en: 'Customize document processing and search pipeline' },
  'settings.chunkSizeDesc': { vi: 'Kích thước mỗi đoạn văn bản khi chia nhỏ tài liệu', en: 'Size of each text segment when splitting documents' },
  'settings.chunkOverlapDesc': { vi: 'Độ chồng lấp giữa các chunks liền kề', en: 'Overlap between adjacent chunks' },
  'settings.topKDesc': { vi: 'Số lượng chunks tối đa trả về khi tìm kiếm', en: 'Maximum chunks returned in search' },
  'settings.vectorStats': { vi: 'Thống kê Vector Database', en: 'Vector Database Statistics' },
  'settings.vectorStatsDesc': { vi: 'Thông tin về dữ liệu đã được index', en: 'Information about indexed data' },
  'settings.totalChunks': { vi: 'Tổng chunks', en: 'Total Chunks' },
  'settings.documents': { vi: 'Tài liệu', en: 'Documents' },
  'settings.dimension': { vi: 'Dimension', en: 'Dimension' },
  'settings.storage': { vi: 'Dung lượng', en: 'Storage' },
  'settings.emailNotif': { vi: 'Thông báo Email', en: 'Email Notifications' },
  'settings.emailNotifConfig': { vi: 'Cấu hình gửi thông báo qua email', en: 'Configure email notification delivery' },
  'settings.emailNotifLabel': { vi: 'Thông báo email', en: 'Email notifications' },
  'settings.emailNotifDesc': { vi: 'Gửi thông báo quan trọng qua email', en: 'Send important notifications via email' },
  'settings.quizReminder': { vi: 'Nhắc nhở Quiz', en: 'Quiz Reminders' },
  'settings.quizReminderDesc': { vi: 'Gửi email nhắc nhở khi có quiz mới', en: 'Send email reminders for new quizzes' },
  'settings.systemAlerts': { vi: 'Cảnh báo hệ thống', en: 'System Alerts' },
  'settings.systemAlertsDesc': { vi: 'Thông báo khi có lỗi hoặc sự cố', en: 'Notify when errors or issues occur' },
  'settings.securitySettings': { vi: 'Cài đặt bảo mật', en: 'Security Settings' },
  'settings.securityDesc': { vi: 'Cấu hình bảo mật và xác thực', en: 'Configure security and authentication' },
  'settings.2fa': { vi: 'Xác thực 2 yếu tố (2FA)', en: 'Two-Factor Authentication (2FA)' },
  'settings.2faDesc': { vi: 'Yêu cầu xác thực 2 bước cho admin', en: 'Require 2-step verification for admins' },
  'settings.loginLimit': { vi: 'Giới hạn đăng nhập sai', en: 'Failed Login Limit' },
  'settings.loginLimitDesc': { vi: 'Khóa tài khoản sau 5 lần đăng nhập sai', en: 'Lock account after 5 failed login attempts' },
  'settings.sessionTimeout': { vi: 'Session Timeout', en: 'Session Timeout' },
  'settings.sessionTimeoutDesc': { vi: 'Tự động đăng xuất sau thời gian không hoạt động', en: 'Auto logout after period of inactivity' },
  'settings.activityLog': { vi: 'Nhật ký hoạt động', en: 'Activity Log' },
  'settings.activityLogDesc': { vi: 'Hoạt động gần đây của quản trị viên', en: 'Recent admin activities' },
  'settings.logLogin': { vi: 'Đăng nhập hệ thống', en: 'System Login' },
  'settings.logUpdateLLM': { vi: 'Cập nhật cấu hình LLM', en: 'Updated LLM Configuration' },
  'settings.logAddUser': { vi: 'Thêm người dùng mới', en: 'Added New User' },
  'settings.logDeleteDoc': { vi: 'Xóa tài liệu', en: 'Deleted Document' },
  'settings.minutes': { vi: 'phút', en: 'minutes' },
  'settings.hours': { vi: 'giờ', en: 'hours' },

  // Profile
  'profile.title': { vi: 'Tài khoản', en: 'Account' },
  'profile.subtitle': { vi: 'Quản lý thông tin cá nhân và cài đặt', en: 'Manage personal information and settings' },
  'profile.info': { vi: 'Hồ sơ', en: 'Profile' },
  'profile.notifications': { vi: 'Thông báo', en: 'Notifications' },
  'profile.activity': { vi: 'Hoạt động', en: 'Activity' },
  'profile.personalInfo': { vi: 'Thông tin cá nhân', en: 'Personal Information' },
  'profile.fullName': { vi: 'Họ và tên', en: 'Full Name' },
  'profile.email': { vi: 'Email', en: 'Email' },
  'profile.emailNote': { vi: 'Email liên kết với Google không thể thay đổi', en: 'Google-linked email cannot be changed' },
  'profile.darkMode': { vi: 'Chế độ tối', en: 'Dark Mode' },
  'profile.darkModeDesc': { vi: 'Chuyển đổi giữa giao diện sáng và tối', en: 'Switch between light and dark theme' },
  'profile.activityStats': { vi: 'Thống kê hoạt động', en: 'Activity Statistics' },
  'profile.courses': { vi: 'Môn học', en: 'Courses' },
  'profile.aiQuestions': { vi: 'Câu hỏi AI', en: 'AI Questions' },
  'profile.quizCompleted': { vi: 'Quiz hoàn thành', en: 'Quiz Completed' },
  'profile.studyTime': { vi: 'Thời gian học', en: 'Study Time' },
  'profile.notifSettings': { vi: 'Cài đặt thông báo', en: 'Notification Settings' },
  'profile.notifDesc': { vi: 'Chọn loại thông báo bạn muốn nhận', en: 'Choose which notifications to receive' },
  'profile.emailNotif': { vi: 'Thông báo Email', en: 'Email Notifications' },
  'profile.emailNotifDesc': { vi: 'Nhận thông báo quan trọng qua email', en: 'Receive important notifications via email' },
  'profile.quizReminder': { vi: 'Nhắc nhở Quiz', en: 'Quiz Reminders' },
  'profile.quizReminderDesc': { vi: 'Nhận thông báo khi có quiz mới hoặc sắp hết hạn', en: 'Get notified about new or expiring quizzes' },
  'profile.activityLog': { vi: 'Nhật ký hoạt động', en: 'Activity Log' },
  'profile.activityLogDesc': { vi: 'Lịch sử hoạt động gần đây', en: 'Recent activity history' },
  'profile.joinedAt': { vi: 'Tham gia từ', en: 'Joined' },
  'profile.language': { vi: 'Ngôn ngữ', en: 'Language' },
  'profile.languageDesc': { vi: 'Chọn ngôn ngữ hiển thị', en: 'Choose display language' },
  'profile.savedDesc': { vi: 'Thông tin tài khoản đã được lưu.', en: 'Account info has been saved.' },

  // Breadcrumbs
  'breadcrumb.dashboard': { vi: 'Dashboard', en: 'Dashboard' },
  'breadcrumb.courses': { vi: 'Môn học', en: 'Courses' },
  'breadcrumb.chat': { vi: 'Chat AI', en: 'AI Chat' },
  'breadcrumb.documents': { vi: 'Tài liệu', en: 'Documents' },
  'breadcrumb.quizzes': { vi: 'Quiz', en: 'Quizzes' },
  'breadcrumb.users': { vi: 'Người dùng', en: 'Users' },
  'breadcrumb.settings': { vi: 'Cài đặt', en: 'Settings' },
  'breadcrumb.profile': { vi: 'Tài khoản', en: 'Account' },

  // Notifications
  'notif.title': { vi: 'Thông báo', en: 'Notifications' },
  'notif.viewAll': { vi: 'Xem tất cả thông báo', en: 'View all notifications' },

  // Login
  'login.welcome': { vi: 'Chào mừng trở lại', en: 'Welcome Back' },
  'login.subtitle': { vi: 'Đăng nhập để tiếp tục hành trình học tập', en: 'Sign in to continue your learning journey' },
  'login.google': { vi: 'Đăng nhập với Google', en: 'Sign in with Google' },
  'login.loading': { vi: 'Đang đăng nhập...', en: 'Signing in...' },
  'login.demoQuick': { vi: 'Demo nhanh', en: 'Quick Demo' },
  'login.heroTitle1': { vi: 'Hệ thống Trợ lý', en: 'AI Learning' },
  'login.heroTitle2': { vi: 'Học tập AI', en: 'Assistant' },
  'login.heroDesc': { vi: 'Nền tảng AI-powered hỗ trợ sinh viên và giáo viên trong việc học tập, giảng dạy hiệu quả hơn với công nghệ RAG.', en: 'AI-powered platform to help students and teachers learn and teach more effectively with RAG technology.' },
  'login.terms': { vi: 'Bằng việc đăng nhập, bạn đồng ý với', en: 'By signing in, you agree to the' },
  'login.termsLink': { vi: 'Điều khoản', en: 'Terms' },
  'login.privacyLink': { vi: 'Chính sách bảo mật', en: 'Privacy Policy' },
  'login.and': { vi: 'và', en: 'and' },
  'login.admin': { vi: 'Quản trị', en: 'Admin' },
  'login.teaching': { vi: 'Giảng dạy', en: 'Teaching' },
  'login.learning': { vi: 'Học tập', en: 'Learning' },
  'login.feature1': { vi: 'Trợ lý AI thông minh', en: 'Smart AI Assistant' },
  'login.feature1Desc': { vi: 'Hỏi đáp dựa trên tài liệu môn học thực tế với RAG', en: 'Q&A based on real course materials with RAG' },
  'login.feature2': { vi: 'Quản lý tài liệu', en: 'Document Management' },
  'login.feature2Desc': { vi: 'Upload và tổ chức slide, giáo trình dễ dàng', en: 'Upload and organize slides, textbooks easily' },
  'login.feature3': { vi: 'Tạo Quiz tự động', en: 'Auto Quiz Generation' },
  'login.feature3Desc': { vi: 'AI tự động tạo câu hỏi ôn tập từ nội dung', en: 'AI auto-generates review questions from content' },
  'login.feature4': { vi: 'Theo dõi tiến độ', en: 'Progress Tracking' },
  'login.feature4Desc': { vi: 'Giáo viên theo dõi học tập của sinh viên', en: 'Teachers track student learning progress' },

  // Toast messages
  'toast.saved': { vi: 'Đã lưu', en: 'Saved' },
  'toast.deleted': { vi: 'Đã xóa', en: 'Deleted' },
  'toast.updated': { vi: 'Đã cập nhật', en: 'Updated' },
  'toast.copied': { vi: 'Đã sao chép', en: 'Copied' },
  'toast.created': { vi: 'Đã tạo', en: 'Created' },
  'toast.uploaded': { vi: 'Đã tải lên', en: 'Uploaded' },
  'toast.downloading': { vi: 'Đang tải xuống', en: 'Downloading' },
  'toast.added': { vi: 'Đã thêm', en: 'Added' },
  'toast.duplicated': { vi: 'Đã nhân bản', en: 'Duplicated' },
  'toast.linkCopied': { vi: 'Đã sao chép link', en: 'Link Copied' },
  'toast.uploading': { vi: 'Đang tải lên', en: 'Uploading' },
  'toast.processDone': { vi: 'Đã xử lý xong', en: 'Processing Complete' },
  'toast.roleChanged': { vi: 'Đã đổi vai trò', en: 'Role Changed' },
  'toast.codeCopied': { vi: 'Đã sao chép mã', en: 'Code Copied' },
  'toast.addedToSystem': { vi: 'đã được thêm vào hệ thống', en: 'has been added to the system' },
  'toast.readyToUse': { vi: 'đã sẵn sàng sử dụng', en: 'is ready to use' },
  'toast.beingProcessed': { vi: 'đang được tải lên và xử lý', en: 'is being uploaded and processed' },
  'toast.quizDeleted': { vi: 'đã được xóa.', en: 'has been deleted.' },
  'toast.quizDuplicated': { vi: 'đã được nhân bản thành công.', en: 'has been duplicated successfully.' },
  'toast.quizLinkCopied': { vi: 'Link quiz đã được sao chép vào clipboard.', en: 'Quiz link has been copied to clipboard.' },
  'toast.quizUpdated': { vi: 'đã được cập nhật.', en: 'has been updated.' },

  // Confirm dialogs
  'confirm.deleteCourse': { vi: 'Xóa môn học', en: 'Delete Course' },
  'confirm.deleteDoc': { vi: 'Xóa tài liệu', en: 'Delete Document' },
  'confirm.deleteQuiz': { vi: 'Xóa quiz', en: 'Delete Quiz' },
  'confirm.deleteUser': { vi: 'Xóa người dùng', en: 'Delete User' },
  'confirm.deleteStudent': { vi: 'Xóa sinh viên khỏi môn', en: 'Remove Student' },
  'confirm.deleteConversation': { vi: 'Xóa cuộc trò chuyện', en: 'Delete Conversation' },
  'confirm.irreversible': { vi: 'Hành động này không thể hoàn tác.', en: 'This action cannot be undone.' },
  'confirm.sure': { vi: 'Bạn có chắc chắn muốn xóa', en: 'Are you sure you want to delete' },
  'confirm.button': { vi: 'Xác nhận xóa', en: 'Confirm Delete' },
  'confirm.quizDeleteDesc': { vi: 'Tất cả câu hỏi và kết quả liên quan sẽ bị mất.', en: 'All related questions and results will be lost.' },

  // Status
  'status.ready': { vi: 'Sẵn sàng', en: 'Ready' },
  'status.processing': { vi: 'Đang xử lý', en: 'Processing' },
  'status.pending': { vi: 'Chờ xử lý', en: 'Pending' },
  'status.error': { vi: 'Lỗi', en: 'Error' },
  'status.active': { vi: 'Hoạt động', en: 'Active' },
  'status.stopped': { vi: 'Ngừng', en: 'Stopped' },

  // Time ago
  'time.minAgo': { vi: 'phút trước', en: 'min ago' },
  'time.hourAgo': { vi: 'giờ trước', en: 'hours ago' },
  'time.dayAgo': { vi: 'ngày trước', en: 'days ago' },

  // Quiz Result
  'quizResult.title': { vi: 'Kết quả Quiz', en: 'Quiz Results' },
  'quizResult.completed': { vi: 'Hoàn thành', en: 'Completed' },
  'quizResult.score': { vi: 'Điểm số', en: 'Score' },
  'quizResult.time': { vi: 'Thời gian', en: 'Time' },
  'quizResult.correct': { vi: 'Đúng', en: 'Correct' },
  'quizResult.wrong': { vi: 'Sai', en: 'Wrong' },
  'quizResult.reviewAnswers': { vi: 'Xem lại đáp án', en: 'Review Answers' },
  'quizResult.yourAnswer': { vi: 'Câu trả lời của bạn', en: 'Your Answer' },
  'quizResult.correctAnswer': { vi: 'Đáp án đúng', en: 'Correct Answer' },
  'quizResult.excellent': { vi: 'Xuất sắc!', en: 'Excellent!' },
  'quizResult.good': { vi: 'Tốt!', en: 'Good!' },
  'quizResult.average': { vi: 'Trung bình', en: 'Average' },
  'quizResult.needImprovement': { vi: 'Cần cải thiện', en: 'Needs Improvement' },
  'quizResult.detailAnswers': { vi: 'Chi tiết câu trả lời', en: 'Answer Details' },
  'quizResult.selected': { vi: 'Đã chọn', en: 'Selected' },
  'quizResult.answer': { vi: 'Đáp án', en: 'Answer' },

  // Quiz Create Dialog
  'quizCreate.title': { vi: 'Tạo Quiz bằng AI', en: 'Create Quiz with AI' },
  'quizCreate.desc': { vi: 'AI sẽ tự động tạo câu hỏi từ tài liệu môn học', en: 'AI will auto-generate questions from course documents' },
  'quizCreate.quizName': { vi: 'Tên Quiz', en: 'Quiz Name' },
  'quizCreate.course': { vi: 'Môn học', en: 'Course' },
  'quizCreate.chapter': { vi: 'Chương / Phạm vi', en: 'Chapter / Scope' },
  'quizCreate.numQuestions': { vi: 'Số câu hỏi', en: 'Number of Questions' },
  'quizCreate.difficulty': { vi: 'Độ khó', en: 'Difficulty' },
  'quizCreate.easy': { vi: 'Dễ', en: 'Easy' },
  'quizCreate.medium': { vi: 'Trung bình', en: 'Medium' },
  'quizCreate.hard': { vi: 'Khó', en: 'Hard' },
  'quizCreate.mixed': { vi: 'Hỗn hợp', en: 'Mixed' },
  'quizCreate.generating': { vi: 'AI đang tạo câu hỏi...', en: 'AI is generating questions...' },
  'quizCreate.create': { vi: 'Tạo Quiz', en: 'Create Quiz' },

  // Edit Dialog
  'edit.title': { vi: 'Chỉnh sửa', en: 'Edit' },
  'edit.saveChanges': { vi: 'Lưu thay đổi', en: 'Save Changes' },

  // Preview Dialog
  'preview.title': { vi: 'Xem trước tài liệu', en: 'Document Preview' },
  'preview.type': { vi: 'Loại file', en: 'File Type' },
  'preview.size': { vi: 'Kích thước', en: 'Size' },
  'preview.content': { vi: 'Nội dung', en: 'Content' },
  'preview.sampleContent': { vi: 'Nội dung mẫu của tài liệu sẽ được hiển thị tại đây. Trong phiên bản thực, nội dung sẽ được trích xuất từ file PDF/DOCX/TXT.', en: 'Sample document content will be displayed here. In production, content will be extracted from PDF/DOCX/TXT files.' },

  // Not Found
  'notFound.title': { vi: 'Trang không tồn tại', en: 'Page Not Found' },
  'notFound.desc': { vi: 'Trang bạn đang tìm kiếm có thể đã bị di chuyển hoặc không tồn tại trong hệ thống EduAssist.', en: 'The page you are looking for may have been moved or does not exist in EduAssist.' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('eduassist-lang');
    return (stored as Language) || 'vi';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('eduassist-lang', lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[key]?.[language] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
